version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: build
          command: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules
            - lib
            - lib-esm
  test:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: test
          command: yarn test

  lint:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: lint
          command: yarn lint

  prettier:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: prettier
          command: ./node_modules/.bin/prettier --check src/**/*

  publish:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: publish
          command: |
            if [[ "${CIRCLE_TAG}" =~ v[0-9]+(\.[0-9]+)+(-[a-zA-Z]+[0-9]*)* ]]; then
              # this will only run if we're in a tag build
              ./scripts/publish.sh
            fi

workflows:
  version: 2
  check:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - prettier:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - build
            - lint
            - prettier
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+){2}(-rc[0-9]+)?/
